# .circleci/config.yml
version: 2.1
jobs:
  beta-android:
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout
      - run: yarn beta-android

  beta-ios:
    macos:
      xcode: 16.0.0
    steps:
      - checkout
      - run: yarn beta-ios

workflows:
  beta:
    jobs:
      - beta-android
      - beta-ios
