# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
  
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
    print "Fastlane works successfully in iOS"
  end

  desc "Create pp on apple developer portal and apple store connect"
  lane :create_app do
    produce(
      username: 'example@email.com', # apple acount
      app_identifier: 'org.reactjs.native.example.CICDProject',
      app_name: 'CICDTutorial',
      language: 'English',
      app_version: '1.0',
      sku: 'cicd_tutorial',
      # team_name: 'SunApps GmbH'  # only necessary when in multiple teams
      )
  end

  desc "Build iOS App"
  lane :build_release_ios do
    match
    gym(
      workspace: 'CICDTutorial.xcworkspace',
      configuration: 'Release',
      scheme: 'CICDTutorial',
    )
  end

  desc "Prepare iOS Build & Distribute to Firebase App distribution"
  lane :beta_ios do
    build_release_ios
    firebase_app_distribution(
      app: "1:917941208183:ios:890b11252509d6a3ad3272",
      firebase_cli_token: "1//03JZkqqWxwpskCgYIARAAGAMSNwF-L9IrWSDrTiLaYnLYGPZzA-jHnXanIFcbHME_XEb7ESI7BAQfccQJ7O49bkNCgyL3l03JFGQ",
      groups: "testers" # group name in firebase
    )
  end
end
