# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    print "Fastlane works successfully in Android"
  end

  desc "Prepare Android Debug Build"
  lane :build_debug_android do
    gradle(
      task: "assembleDebug",
    )
  end

  desc "Prepare Release Debug Build"
  lane :build_release_android do
    gradle(
      task: "assembleRelease",
    )
  end

  desc "Prepare Android Build & Distribute to Firebase App distribution"
  lane :beta_android do
    build_release_android
    firebase_app_distribution(
      app: "1:917941208183:android:60961378ac58332fad3272",
      firebase_cli_token: "1//03JZkqqWxwpskCgYIARAAGAMSNwF-L9IrWSDrTiLaYnLYGPZzA-jHnXanIFcbHME_XEb7ESI7BAQfccQJ7O49bkNCgyL3l03JFGQ",
      groups: "testers" # group name in firebase
    )

  end

end
